"""測試矩陣的商業情境資料(3 種商業變型)。文字用 {key} 佔位,由 gen_matrix 依語言渲染:
en → 英文詞;zh-TW → 中文詞(台灣用語);mixed → 中文句子 + 英文詞(實體用 Symbol,動作用英文動詞)。"""

S1 = {
    "id": "s1", "ctx": "Orders", "feature": "order", "issue": "order-cancel",
    "title": {"en": "Order cancellation and refund", "zh": "訂單取消與退款"},
    "terms": {
        "order": {"zh": "訂單", "en": "order", "sym": "Order", "kind": "entity"},
        "refund": {"zh": "退款單", "en": "refund", "sym": "Refund", "kind": "entity"},
        "payment_gateway": {"zh": "付款閘道", "en": "payment gateway", "sym": "PaymentGateway", "kind": "external"},
        "customer": {"zh": "顧客", "en": "customer", "sym": "Customer", "kind": "role"},
        "support_agent": {"zh": "客服人員", "en": "support agent", "sym": "SupportAgent", "kind": "role"},
        "system": {"zh": "系統", "en": "system", "sym": "System", "kind": "role"},
        "cancel": {"zh": "取消", "en": "cancel", "sym": "CancelOrder", "kind": "action"},
        "issue_refund": {"zh": "退款", "en": "refund", "sym": "IssueRefund", "kind": "action"},
        "view_history": {"zh": "查看", "en": "view", "sym": "ListCancellations", "kind": "action"},
        "placed": {"zh": "已下單", "en": "placed", "sym": "Placed", "kind": "status"},
        "shipped": {"zh": "已出貨", "en": "shipped", "sym": "Shipped", "kind": "status"},
        "cancelled": {"zh": "已取消", "en": "cancelled", "sym": "Cancelled", "kind": "status"},
        "refunded": {"zh": "已退款", "en": "refunded", "sym": "Refunded", "kind": "status"},
    },
    "existing_entity": {"key": "order", "file_states": ["Placed", "Shipped"], "behavior": "Shipped",
                         "behavior_line": "public OrderStatus Status { get; private set; } = OrderStatus.Placed;"},
    "new_entity": "refund",
    "state_entity": "order",
    "states": ["Placed", "Shipped", "Cancelled", "Refunded"],
    "transitions": [("[*]", "Placed", "PlaceOrder"), ("Placed", "Shipped", "Ship"), ("Placed", "Cancelled", "CancelOrder"), ("Cancelled", "Refunded", "IssueRefund")],
    "existing_query": {"sym": "GetOrder", "method": "GET", "path": "/orders/{id}"},
    "controller": "OrdersController", "page": "OrderDetailPage", "store": "orderStore", "client": "ordersApi", "table": "Orders",
    "external": {"key": "payment_gateway", "client": "PaymentGatewayClient", "iface": "IPaymentGateway", "method": "RefundAsync"},
    "actions": [
        {"key": "cancel", "actor": "customer", "kind": "command", "method": "POST", "path": "/orders/{id}/cancel", "component": "CancelOrderDialog", "external": False},
        {"key": "issue_refund", "actor": "system", "kind": "command", "method": "POST", "path": "/orders/{id}/refund", "component": None, "external": True},
        {"key": "view_history", "actor": "support_agent", "kind": "query", "method": "GET", "path": "/orders/cancellations", "component": "CancellationHistoryTable", "external": False},
    ],
    "reqs": [
        {"id": "REQ-001", "anchor": "3.1", "types": "functional, state_heavy", "actions": ["cancel"],
         "title": {"en": "A {customer} can {cancel} an {order} before it is {shipped}", "zh": "{customer}可在出貨前{cancel}{order}"},
         "pm": {"en": "A {customer} can {cancel} an {order} while it is {placed}. An {order} that is already {shipped} cannot be cancelled. After {cancel}, the {order} status becomes {cancelled}.",
                "zh": "{customer}可以在{order}狀態為{placed}時{cancel}{order}。{order}一旦{shipped}就不可{cancel}。{cancel}後{order}狀態改為{cancelled}。"},
         "acs": [("AC-001-1", {"en": ("an {order} is {placed}", "the {customer} cancels it", "the {order} status is {cancelled}"),
                               "zh": ("{order}狀態為{placed}", "{customer}{cancel}{order}", "{order}狀態為{cancelled}")}),
                 ("AC-001-2", {"en": ("an {order} is {shipped}", "the {customer} cancels it", "the response is 409 ORDER_SHIPPED and the status is unchanged"),
                               "zh": ("{order}狀態為{shipped}", "{customer}{cancel}{order}", "回應 409 ORDER_SHIPPED,狀態不變")})]},
        {"id": "REQ-002", "anchor": "3.2", "types": "functional, integration", "actions": ["issue_refund"],
         "title": {"en": "The {system} issues a {refund} through the {payment_gateway} after cancellation", "zh": "{cancel}後{system}經{payment_gateway}{issue_refund}"},
         "pm": {"en": "After an {order} is {cancelled}, the {system} issues a {refund} through the {payment_gateway}. When the {payment_gateway} fails, the {system} retries up to 3 times and keeps the {order} {cancelled}. A successful {refund} marks the {order} as {refunded}.",
                "zh": "{order}{cancelled}後,{system}透過{payment_gateway}{issue_refund}。{payment_gateway}失敗時{system}最多重試 3 次,{order}維持{cancelled}。{issue_refund}成功後{order}狀態改為{refunded}。"},
         "acs": [("AC-002-1", {"en": ("an {order} is {cancelled} and paid", "the {system} issues the {refund}", "the {payment_gateway} is called and the {order} is {refunded}"),
                               "zh": ("{order}已{cancel}且已付款", "{system}{issue_refund}", "呼叫{payment_gateway},{order}狀態為{refunded}")}),
                 ("AC-002-2", {"en": ("the {payment_gateway} times out", "the {system} issues the {refund}", "it retries 3 times and the {order} stays {cancelled}"),
                               "zh": ("{payment_gateway}逾時", "{system}{issue_refund}", "重試 3 次,{order}維持{cancelled}")})]},
        {"id": "REQ-003", "anchor": "3.3", "types": "functional", "actions": ["view_history"],
         "title": {"en": "A {support_agent} can {view_history} the cancellation history", "zh": "{support_agent}可{view_history}{cancel}紀錄"},
         "pm": {"en": "A {support_agent} can {view_history} the cancellation history of every {order}, including time and reason.",
                "zh": "{support_agent}可以{view_history}每筆{order}的{cancel}紀錄,包含時間與原因。"},
         "acs": [("AC-003-1", {"en": ("{order} records were {cancelled}", "the {support_agent} opens the history", "each row shows the {order}, time and reason"),
                               "zh": ("有{order}已{cancel}", "{support_agent}開啟紀錄", "每列顯示{order}、時間與原因")})]},
    ],
    "nfr": {"id": "NFR-001", "action": "issue_refund", "measure": "P95 < 5 min",
            "pm": {"en": "A {refund} must finish within 5 minutes after cancellation for 95% of {order} records.", "zh": "95% 的{order}在{cancel}後 5 分鐘內完成{issue_refund}。"}},
    "background": {"en": "Today a {customer} must phone support to {cancel} an {order}. Goal: self-service {cancel} and automatic {refund} through the {payment_gateway}.",
                   "zh": "目前{customer}要{cancel}{order}必須打電話給客服。目標:{customer}自助{cancel},並由{system}經{payment_gateway}自動{issue_refund}。"},
    "users": {"en": "{customer}: wants to {cancel} an {order} quickly. {support_agent}: needs the cancellation history. {system}: issues the {refund}.",
              "zh": "{customer}:想快速{cancel}{order}。{support_agent}:需要{view_history}{cancel}紀錄。{system}:負責{issue_refund}。"},
}

S2 = {
    "id": "s2", "ctx": "Rooms", "feature": "booking", "issue": "room-booking",
    "title": {"en": "Meeting room booking", "zh": "會議室預約"},
    "terms": {
        "room": {"zh": "會議室", "en": "meeting room", "sym": "Room", "kind": "entity"},
        "booking": {"zh": "預約單", "en": "booking", "sym": "Booking", "kind": "entity"},
        "time_slot": {"zh": "時段", "en": "time slot", "sym": "TimeSlot", "kind": "entity"},
        "calendar": {"zh": "行事曆服務", "en": "calendar service", "sym": "CalendarService", "kind": "external"},
        "employee": {"zh": "員工", "en": "employee", "sym": "Employee", "kind": "role"},
        "admin": {"zh": "管理員", "en": "admin", "sym": "Admin", "kind": "role"},
        "system": {"zh": "系統", "en": "system", "sym": "System", "kind": "role"},
        "book": {"zh": "預約", "en": "book", "sym": "BookRoom", "kind": "action"},
        "check_in": {"zh": "報到", "en": "check in", "sym": "CheckInBooking", "kind": "action"},
        "release": {"zh": "釋放", "en": "release", "sym": "ReleaseNoShow", "kind": "action"},
        "view_daily": {"zh": "查看", "en": "view", "sym": "ListDailyBookings", "kind": "action"},
        "booked": {"zh": "已預約", "en": "booked", "sym": "Booked", "kind": "status"},
        "checked_in": {"zh": "已報到", "en": "checked-in", "sym": "CheckedIn", "kind": "status"},
        "released": {"zh": "已釋放", "en": "released", "sym": "Released", "kind": "status"},
    },
    "existing_entity": {"key": "room", "file_states": [], "behavior": "Capacity",
                         "behavior_line": "public int Capacity { get; private set; }"},
    "new_entity": "booking",
    "state_entity": "booking",
    "states": ["Booked", "CheckedIn", "Released"],
    "transitions": [("[*]", "Booked", "BookRoom"), ("Booked", "CheckedIn", "CheckInBooking"), ("Booked", "Released", "ReleaseNoShow")],
    "existing_query": {"sym": "ListRooms", "method": "GET", "path": "/rooms"},
    "controller": "RoomsController", "page": "RoomBookingPage", "store": "bookingStore", "client": "roomsApi", "table": "Rooms",
    "external": {"key": "calendar", "client": "CalendarServiceClient", "iface": "ICalendarService", "method": "SyncAsync"},
    "actions": [
        {"key": "book", "actor": "employee", "kind": "command", "method": "POST", "path": "/rooms/{id}/bookings", "component": "BookingForm", "external": True},
        {"key": "check_in", "actor": "employee", "kind": "command", "method": "POST", "path": "/bookings/{id}/check-in", "component": "CheckInButton", "external": False},
        {"key": "release", "actor": "system", "kind": "job", "method": None, "path": None, "component": None, "external": True},
        {"key": "view_daily", "actor": "admin", "kind": "query", "method": "GET", "path": "/bookings/daily", "component": "DailyBookingTable", "external": False},
    ],
    "reqs": [
        {"id": "REQ-001", "anchor": "3.1", "types": "functional, domain_rich", "actions": ["book"],
         "title": {"en": "An {employee} can {book} a {room} without overlapping {time_slot}", "zh": "{employee}可{book}{room},{time_slot}不得重疊"},
         "pm": {"en": "An {employee} can {book} a {room} for a {time_slot}. Two {booking} records on the same {room} must not overlap. A new {booking} is {booked} and is synced to the {calendar}.",
                "zh": "{employee}可以為某個{time_slot}{book}{room}。同一{room}的兩張{booking}不得重疊。新{booking}狀態為{booked},並同步到{calendar}。"},
         "acs": [("AC-001-1", {"en": ("the {time_slot} is free", "the {employee} books the {room}", "a {booking} is {booked}"),
                               "zh": ("{time_slot}空閒", "{employee}{book}{room}", "{booking}狀態為{booked}")}),
                 ("AC-001-2", {"en": ("the {time_slot} overlaps another {booking}", "the {employee} books the {room}", "the response is 409 SLOT_TAKEN"),
                               "zh": ("{time_slot}與其他{booking}重疊", "{employee}{book}{room}", "回應 409 SLOT_TAKEN")})]},
        {"id": "REQ-002", "anchor": "3.2", "types": "functional, state_heavy, integration", "actions": ["check_in", "release"],
         "title": {"en": "{check_in} within 15 minutes or the {system} will {release} the {room}", "zh": "15 分鐘內{check_in},否則{system}{release}{room}"},
         "pm": {"en": "The {employee} must {check_in} within 15 minutes after the start. Otherwise the {system} will {release} the {booking}, marks it {released} and updates the {calendar}.",
                "zh": "{employee}必須在開始後 15 分鐘內{check_in}。否則{system}{release}{booking},狀態改為{released},並更新{calendar}。"},
         "acs": [("AC-002-1", {"en": ("a {booking} is {booked}", "the {employee} checks in within 15 minutes", "the {booking} is {checked_in}"),
                               "zh": ("{booking}狀態為{booked}", "{employee}在 15 分鐘內{check_in}", "{booking}狀態為{checked_in}")}),
                 ("AC-002-2", {"en": ("no check in after 15 minutes", "the {system} job runs", "the {booking} is {released} and the {calendar} is updated"),
                               "zh": ("15 分鐘內未{check_in}", "{system}排程執行", "{booking}狀態為{released},{calendar}已更新")})]},
        {"id": "REQ-003", "anchor": "3.3", "types": "functional", "actions": ["view_daily"],
         "title": {"en": "An {admin} can {view_daily} daily {booking} records", "zh": "{admin}可{view_daily}每日{booking}"},
         "pm": {"en": "An {admin} can {view_daily} all {booking} records of a day for every {room}.", "zh": "{admin}可以{view_daily}每間{room}當天的所有{booking}。"},
         "acs": [("AC-003-1", {"en": ("{booking} records exist today", "the {admin} opens the daily view", "rows are grouped by {room}"),
                               "zh": ("今天有{booking}", "{admin}開啟每日檢視", "依{room}分組顯示")})]},
    ],
    "nfr": {"id": "NFR-001", "action": "book", "measure": "100 concurrent → 1 success",
            "pm": {"en": "With 100 concurrent requests for the same {time_slot}, exactly one {booking} succeeds.", "zh": "同一{time_slot}有 100 個並行{book}請求時,只有一張{booking}成功。"}},
    "background": {"en": "An {employee} books a {room} by email today and double booking happens weekly. Goal: self-service {book} with conflict checks and automatic {release}.",
                   "zh": "目前{employee}用 email {book}{room},每週都有重複{book}。目標:自助{book},檢查衝突,並自動{release}未{check_in}的{room}。"},
    "users": {"en": "{employee}: wants to {book} a {room}. {admin}: needs the daily view. {system}: will {release} no-show {booking} records.",
              "zh": "{employee}:想{book}{room}。{admin}:需要每日{view_daily}。{system}:{release}未{check_in}的{booking}。"},
}

S3 = {
    "id": "s3", "ctx": "Loyalty", "feature": "rewards", "issue": "points-redemption",
    "title": {"en": "Loyalty points redemption", "zh": "會員點數兌換"},
    "terms": {
        "points_account": {"zh": "點數帳戶", "en": "points account", "sym": "PointsAccount", "kind": "entity"},
        "redemption": {"zh": "兌換單", "en": "redemption", "sym": "Redemption", "kind": "entity"},
        "reward": {"zh": "獎品", "en": "reward", "sym": "Reward", "kind": "entity"},
        "transaction": {"zh": "點數交易", "en": "points transaction", "sym": "PointTransaction", "kind": "entity"},
        "vendor": {"zh": "獎品供應商", "en": "reward vendor", "sym": "RewardVendor", "kind": "external"},
        "member": {"zh": "會員", "en": "member", "sym": "Member", "kind": "role"},
        "system": {"zh": "系統", "en": "system", "sym": "System", "kind": "role"},
        "redeem": {"zh": "兌換", "en": "redeem", "sym": "RedeemReward", "kind": "action"},
        "expire": {"zh": "到期", "en": "expire", "sym": "ExpirePoints", "kind": "action"},
        "view_tx": {"zh": "查看", "en": "view", "sym": "ListTransactions", "kind": "action"},
        "pending": {"zh": "待兌換", "en": "pending", "sym": "Pending", "kind": "status"},
        "fulfilled": {"zh": "已兌換", "en": "completed", "sym": "Fulfilled", "kind": "status"},
    },
    "existing_entity": {"key": "points_account", "file_states": [], "behavior": "Balance",
                         "behavior_line": "public int Balance { get; private set; }"},
    "new_entity": "redemption",
    "state_entity": "redemption",
    "states": ["Pending", "Fulfilled", "Failed"],
    "transitions": [("[*]", "Pending", "RedeemReward"), ("Pending", "Fulfilled", "VendorConfirmed"), ("Pending", "Failed", "VendorRejected")],
    "existing_query": {"sym": "GetBalance", "method": "GET", "path": "/members/{id}/points"},
    "controller": "PointsController", "page": "RewardsPage", "store": "rewardsStore", "client": "pointsApi", "table": "PointsAccounts",
    "external": {"key": "vendor", "client": "RewardVendorClient", "iface": "IRewardVendor", "method": "FulfillAsync"},
    "actions": [
        {"key": "redeem", "actor": "member", "kind": "command", "method": "POST", "path": "/members/{id}/redemptions", "component": "RedeemDialog", "external": True},
        {"key": "expire", "actor": "system", "kind": "job", "method": None, "path": None, "component": None, "external": False},
        {"key": "view_tx", "actor": "member", "kind": "query", "method": "GET", "path": "/members/{id}/transactions", "component": "TransactionList", "external": False},
    ],
    "reqs": [
        {"id": "REQ-001", "anchor": "3.1", "types": "functional, domain_rich, integration", "actions": ["redeem"],
         "title": {"en": "A {member} can {redeem} a {reward} when the {points_account} has enough points", "zh": "{points_account}點數足夠時{member}可{redeem}{reward}"},
         "pm": {"en": "A {member} can {redeem} a {reward} when the {points_account} balance covers the cost. The {redemption} starts {pending}, the points are deducted as a {transaction}, and the {vendor} fulfills it.",
                "zh": "{points_account}餘額足夠時,{member}可以{redeem}{reward}。{redemption}初始為{pending},扣點記為一筆{transaction},由{vendor}出貨。"},
         "acs": [("AC-001-1", {"en": ("the balance covers the {reward}", "the {member} redeems it", "a {redemption} is created and the {vendor} is called"),
                               "zh": ("餘額足夠", "{member}{redeem}{reward}", "建立{redemption}並呼叫{vendor}")}),
                 ("AC-001-2", {"en": ("the balance is not enough", "the {member} redeems it", "the response is 422 INSUFFICIENT_POINTS and nothing is deducted"),
                               "zh": ("餘額不足", "{member}{redeem}{reward}", "回應 422 INSUFFICIENT_POINTS,不扣點")})]},
        {"id": "REQ-002", "anchor": "3.2", "types": "functional, data", "actions": ["expire"],
         "title": {"en": "Points {expire} after 12 months", "zh": "點數 12 個月後{expire}"},
         "pm": {"en": "Points that are not used for 12 months {expire}. A monthly {system} job writes an expiry {transaction} and reduces the {points_account} balance.",
                "zh": "12 個月未使用的點數會{expire}。{system}每月排程寫一筆{expire}{transaction},並扣減{points_account}餘額。"},
         "acs": [("AC-002-1", {"en": ("points were earned 13 months ago", "the monthly job runs", "an expiry {transaction} is written and the balance drops"),
                               "zh": ("點數於 13 個月前取得", "每月排程執行", "寫入{expire}{transaction},餘額減少")})]},
        {"id": "REQ-003", "anchor": "3.3", "types": "functional", "actions": ["view_tx"],
         "title": {"en": "A {member} can {view_tx} each {transaction}", "zh": "{member}可{view_tx}{transaction}"},
         "pm": {"en": "A {member} can {view_tx} every {transaction} with date, type and points.", "zh": "{member}可以{view_tx}每筆{transaction},含日期、類型與點數。"},
         "acs": [("AC-003-1", {"en": ("the {member} has a {transaction}", "the {member} opens the history", "each {transaction} shows date, type and points"),
                               "zh": ("{member}有{transaction}", "{member}開啟紀錄", "每筆{transaction}顯示日期、類型、點數")})]},
    ],
    "nfr": {"id": "NFR-001", "action": "redeem", "measure": "balance never negative",
            "pm": {"en": "The {points_account} balance must never become negative, even with concurrent redemption.", "zh": "即使並行{redeem},{points_account}餘額也不得為負。"}},
    "background": {"en": "A {member} collects points but cannot {redeem} them online. Goal: online {redeem} of a {reward} with a reliable ledger.",
                   "zh": "{member}累積點數卻無法線上{redeem}。目標:線上{redeem}{reward},並維持可靠的點數帳本。"},
    "users": {"en": "{member}: wants to {redeem} a {reward}. {system}: will {expire} old points.",
              "zh": "{member}:想{redeem}{reward}並{view_tx}{transaction}。{system}:讓舊點數{expire}。"},
}

SCENARIOS = {"s1": S1, "s2": S2, "s3": S3}
SHAPES = ["fs-front", "fs-back", "fs-balance", "fe-only", "be-only"]
LANGS = ["en", "zh-TW", "mixed"]   # 語言維度代碼;情境資料裡的 "zh" 只是中文措辭的字典鍵

def pairwise():
    """成對覆蓋:shape i、lang j → scenario (i + j) mod 3。任兩維度的每一組合都至少出現一次(15 份)。"""
    out = []
    for i, shape in enumerate(SHAPES):
        for j, lang in enumerate(LANGS):
            out.append((shape, lang, f"s{(i + j) % 3 + 1}"))
    return out
